UPDATE public.site_items SET gallery = '["/assets/ref/imoveis/apartamento-itapema-sc/01.webp","/assets/ref/imoveis/apartamento-itapema-sc/02.webp","/assets/ref/imoveis/apartamento-itapema-sc/03.webp","/assets/ref/imoveis/apartamento-itapema-sc/04.webp","/assets/ref/imoveis/apartamento-itapema-sc/05.webp","/assets/ref/imoveis/apartamento-itapema-sc/06.webp","/assets/ref/imoveis/apartamento-itapema-sc/07.webp","/assets/ref/imoveis/apartamento-itapema-sc/08.webp","/assets/ref/imoveis/apartamento-itapema-sc/09.webp","/assets/ref/imoveis/apartamento-itapema-sc/10.webp","/assets/ref/imoveis/apartamento-itapema-sc/11.webp","/assets/ref/imoveis/apartamento-itapema-sc/12.webp","/assets/ref/imoveis/apartamento-itapema-sc/13.webp","/assets/ref/imoveis/apartamento-itapema-sc/14.webp","/assets/ref/imoveis/apartamento-itapema-sc/15.webp","/assets/ref/imoveis/apartamento-itapema-sc/16.webp","/assets/ref/imoveis/apartamento-itapema-sc/17.webp","/assets/ref/imoveis/apartamento-itapema-sc/18.webp","/assets/ref/imoveis/apartamento-itapema-sc/19.webp","/assets/ref/imoveis/apartamento-itapema-sc/20.webp","/assets/ref/imoveis/apartamento-itapema-sc/21.webp","/assets/ref/imoveis/apartamento-itapema-sc/22.webp","/assets/ref/imoveis/apartamento-itapema-sc/23.webp","/assets/ref/imoveis/apartamento-itapema-sc/24.webp","/assets/ref/imoveis/apartamento-itapema-sc/25.webp","/assets/ref/imoveis/apartamento-itapema-sc/26.webp","/assets/ref/imoveis/apartamento-itapema-sc/27.webp","/assets/ref/imoveis/apartamento-itapema-sc/28.webp","/assets/ref/imoveis/apartamento-itapema-sc/29.webp","/assets/ref/imoveis/apartamento-itapema-sc/30.webp","/assets/ref/imoveis/apartamento-itapema-sc/31.webp"]'::jsonb, updated_at = now() WHERE section = 'imoveis' AND slug = 'apartamento-itapema-sc';

UPDATE public.site_items SET gallery = '["/assets/ref/imoveis/apartamento-porto-belo-sc/01.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/02.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/03.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/04.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/05.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/06.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/07.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/08.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/09.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/10.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/11.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/12.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/13.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/14.webp","/assets/ref/imoveis/apartamento-porto-belo-sc/15.webp"]'::jsonb, updated_at = now() WHERE section = 'imoveis' AND slug = 'apartamento-porto-belo-sc';

UPDATE public.site_items SET gallery = '["/assets/ref/imoveis/gold-shopping/01.webp","/assets/ref/imoveis/gold-shopping/02.webp","/assets/ref/imoveis/gold-shopping/03.webp","/assets/ref/imoveis/gold-shopping/04.webp","/assets/ref/imoveis/gold-shopping/05.webp","/assets/ref/imoveis/gold-shopping/06.webp","/assets/ref/imoveis/gold-shopping/07.webp","/assets/ref/imoveis/gold-shopping/08.webp","/assets/ref/imoveis/gold-shopping/09.webp","/assets/ref/imoveis/gold-shopping/10.webp","/assets/ref/imoveis/gold-shopping/11.webp","/assets/ref/imoveis/gold-shopping/12.webp","/assets/ref/imoveis/gold-shopping/13.webp","/assets/ref/imoveis/gold-shopping/14.webp","/assets/ref/imoveis/gold-shopping/15.webp"]'::jsonb, updated_at = now() WHERE section = 'imoveis' AND slug = 'gold-shopping';

UPDATE public.site_items SET gallery = '["/assets/ref/imoveis/terreno-bairro-santo-antonio/01.webp","/assets/ref/imoveis/terreno-bairro-santo-antonio/02.webp"]'::jsonb, updated_at = now() WHERE section = 'imoveis' AND slug = 'terreno-bairro-santo-antonio';

UPDATE public.site_items SET gallery = '["/assets/ref/imoveis/terreno-bairro-wincler/01.webp","/assets/ref/imoveis/terreno-bairro-wincler/02.webp"]'::jsonb, updated_at = now() WHERE section = 'imoveis' AND slug = 'terreno-bairro-wincler';

UPDATE public.site_items SET gallery = '["/assets/ref/imoveis/terreno-e-casa-em-igrejinha/01.webp","/assets/ref/imoveis/terreno-e-casa-em-igrejinha/02.webp","/assets/ref/imoveis/terreno-e-casa-em-igrejinha/03.webp","/assets/ref/imoveis/terreno-e-casa-em-igrejinha/04.webp","/assets/ref/imoveis/terreno-e-casa-em-igrejinha/05.webp","/assets/ref/imoveis/terreno-e-casa-em-igrejinha/06.webp","/assets/ref/imoveis/terreno-e-casa-em-igrejinha/07.webp","/assets/ref/imoveis/terreno-e-casa-em-igrejinha/08.webp","/assets/ref/imoveis/terreno-e-casa-em-igrejinha/09.webp","/assets/ref/imoveis/terreno-e-casa-em-igrejinha/10.webp"]'::jsonb, updated_at = now() WHERE section = 'imoveis' AND slug = 'terreno-e-casa-em-igrejinha';

UPDATE public.site_items SET gallery = '["/assets/ref/imoveis/terreno-morada-da-patria/01.webp","/assets/ref/imoveis/terreno-morada-da-patria/02.webp"]'::jsonb, updated_at = now() WHERE section = 'imoveis' AND slug = 'terreno-morada-da-patria';