// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anqvmuufszvjvfnktefe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFucXZtdXVmc3p2anZmbmt0ZWZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2OTI3MDQsImV4cCI6MjA4OTI2ODcwNH0.gs49zwGfa6GzwCirSi8cCuDAVD0GCSFZRghoH9-s5HM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});